let appPromise: Promise<any> | undefined;

function loadApp() {
  // @ts-expect-error app.mjs is generated by the API build before Vercel bundles functions.
  appPromise ??= import("../artifacts/api-server/dist/app.mjs").then((module) => module.default);
  return appPromise;
}

export default async function handler(req: any, res: any) {
  const app = await loadApp();
  return app(req, res);
}
